services:
  postgres:
    image: postgres:15
    container_name: nfe-postgres
    environment:
      POSTGRES_DB: nfe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nfe-network

  api:
    build:
      context: .
      dockerfile: Nfe.Api/Dockerfile
    container_name: nfe-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=nfe_db;Username=postgres;Password=postgres;Port=5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - nfe-network

volumes:
  postgres_data:

networks:
  nfe-network:
    driver: bridge